{% set name = "types-dataclasses" %}
{% set version = "0.6.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-dataclasses-{{ version }}.tar.gz
  sha256: 6568532fed11f854e4db2eb48063385b323b93ecadd09f10a215d56246c306d7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/dataclasses-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for dataclasses
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
